// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pieshop.Models;

namespace pieshop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pieshop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fungus Pies",
                            Description = "All fungus-based pies"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Fruit Pies",
                            Description = "All pies made from alien fruits"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bean Pies",
                            Description = "Pies with bean fillings"
                        });
                });

            modelBuilder.Entity("pieshop.Models.Pie", b =>
                {
                    b.Property<int>("PieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AllergyInformation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPieOfTheWeek")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            PieId = 1,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "",
                            ImageUrl = "/images/brain.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "",
                            Name = "Brain Pie",
                            Price = 15.95m,
                            ShortDescription = "Made with false morel (Gyromitra esculenta)"
                        },
                        new
                        {
                            PieId = 2,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "",
                            ImageUrl = "/images/bleeding-tooth.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "",
                            Name = "Bleeding Tooth Pie",
                            Price = 16.00m,
                            ShortDescription = "Made with Hydnellum pecki"
                        },
                        new
                        {
                            PieId = 3,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "",
                            ImageUrl = "/images/glow.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "",
                            Name = "Glow Pie",
                            Price = 12.50m,
                            ShortDescription = "Made with bioluminiscent mushrooms"
                        },
                        new
                        {
                            PieId = 4,
                            AllergyInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "",
                            ImageUrl = "/images/pepino.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "",
                            Name = "Pepino Pie",
                            Price = 16.75m,
                            ShortDescription = "Made with Pepino Fruit from South America"
                        },
                        new
                        {
                            PieId = 5,
                            AllergyInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "",
                            ImageUrl = "/images/kumquat.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "",
                            Name = "Kumquat Pie",
                            Price = 14.25m,
                            ShortDescription = "Made with Kumquat Fruit from China"
                        },
                        new
                        {
                            PieId = 6,
                            AllergyInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "",
                            ImageUrl = "/images/kiwano.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "",
                            Name = "Kiwano Pie",
                            Price = 15.75m,
                            ShortDescription = "Made with Kiwano Fruit from South Africa"
                        },
                        new
                        {
                            PieId = 7,
                            AllergyInformation = "",
                            CategoryId = 3,
                            ImageThumbnailUrl = "",
                            ImageUrl = "/images/bean.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "",
                            Name = "Navy Bean Pie",
                            Price = 13.99m,
                            ShortDescription = "With butter, chocolate, and vanilla"
                        },
                        new
                        {
                            PieId = 8,
                            AllergyInformation = "",
                            CategoryId = 3,
                            ImageThumbnailUrl = "",
                            ImageUrl = "/images/red-bean.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "",
                            Name = "Sweet Red Bean Pie",
                            Price = 14.50m,
                            ShortDescription = "Made with read beans"
                        },
                        new
                        {
                            PieId = 9,
                            AllergyInformation = "",
                            CategoryId = 3,
                            ImageThumbnailUrl = "",
                            ImageUrl = "/images/edamame.jpg",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "",
                            Name = "Edamame Pie",
                            Price = 16.25m,
                            ShortDescription = "Made with edamame beans, mozarella, and zucchini"
                        });
                });

            modelBuilder.Entity("pieshop.Models.Pie", b =>
                {
                    b.HasOne("pieshop.Models.Category", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
